// Code generated by Arduino IoT Cloud, DO NOT EDIT.

#include <string.h>
#include <ArduinoIoTCloud.h>
#include <Arduino_ConnectionHandler.h>
#include "arduino_secrets.h"

const char DEVICE_LOGIN_NAME[]  = "9b40769f-0487-4897-84e7-804c04a483b7";

const char SSID[]               = SECRET_SSID;    // Network SSID (name)
const char PASS[]               = SECRET_OPTIONAL_PASS;    // Network password (use for WPA, or use as key for WEP)
const char DEVICE_KEY[]  = SECRET_DEVICE_KEY;    // Secret device password


float hum;
float temp;
CloudIlluminance lDR;


NotecardConnectionHandler ArduinoIoTPreferredConnection(DEVICE_LOGIN_NAME);

void initProperties(){

  // ArduinoCloud.setBoardId(DEVICE_LOGIN_NAME);
  // ArduinoCloud.setSecretDeviceKey(DEVICE_KEY);
  ArduinoCloud.addProperty(hum, READ, 10 * SECONDS, NULL);
  ArduinoCloud.addProperty(temp, READ, 10 * SECONDS, NULL);
  ArduinoCloud.addProperty(lDR, READ, 10 * SECONDS, NULL);
  ArduinoIoTPreferredConnection.setWiFiCredentials(SSID, PASS);

}
